title: "Herman Orlando Morales López | Ronin Dev"
description: "Senior Full Stack developer, UX-UI and Symfony PHP specialist <br/> from GT 🇬🇹. Martial arts lover 🥋🥊"
buttonText: "Available for work!!"
buttonURL: "https://www.linkedin.com/in/hackemate/"
image: "./images/me.png"
featuredImages:
  - "./images/header-image-01.jpg"
  - "./images/header-image-02.jpg"
  - "./images/header-image-03.jpg"
logoURL: "./images/imagologo.png"
xURL: "https://x.com/hackemateninja"
gitHubURL: "https://github.com/hackemateninja"
facebookURL: "https://www.facebook.com/ronindevninja"
copyright: "Herman Morales. All rights reserved"
